# Generated by Django 4.1.7 on 2023-03-10 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_days_weekend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='days',
            name='weekend',
        ),
    ]
